CREATE TABLE IF NOT EXISTS `users`(
    `id` INT(8) NOT NULL AUTO_INCREMENT,
    `firtname` VARCHAR(45) NOT NULL,
    `lastname` VARCHAR(45) NOT NULL,
    `email` VARCHAR(30) NOT NULL,
    `password` VARCHAR(2048) NOT NULL,
    `created` DATETIME,
    `modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
) ENGINE = InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=20;